services:
  plugin-listing:
    image: senither/dalamud-plugin-listing:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'APP_ADDR=0.0.0.0:8080'
    ports:
      - "8080:8080"
